### ISSUE TITLE
Issues with latest glib

### ISSUE THREAD

**Issue by gregier** [pavouk/lgi#132] opened 2016-03-13 19:18 UTC
glib added a boatload of annotations in commit [25a7c817d3cbef8b6508b44bca6d0b01ca77916b](https://git.gnome.org/browse/glib/commit/?id=25a7c817d3cbef8b6508b44bca6d0b01ca77916b).

These annotations have broken various operations and `make check` spews:
`Error raised while calling 'lgi.cbk (function: 0x40ab6160): GObject': ./lgi/class.lua:303: bad argument #2 to 'new' (number expected, got userdata)`

However, fixing that warning just causes many more warnings to become visible and then the tests crash.

**Comment by pavouk** [comment] 2016-03-28 14:09
This is actually all a result of single incorrect annotation which landed in the glib commit you mentioned.  The incorrect annotation is adding `(out)` to `return_value` argument of `g_closure_invoke`.  Although it seems tempting at first glance, it is grossly incorrect, because `return_value` is actually input argument for `g_closure_invoke`, because g_closure_invoke expects `GValue` which is already initialized with expected return type. The fact that `return_value` is later during g_closure_invoke run modified with result value of clsure invocation has no effect to the actual annotation of that argument.

Note that annotating it to (inout) is incorrect too, because in this case goi client expects that its signature is actually `GValue **return_value` and that input value is completely discarded and replaced with new instance of GValue, which is definitely not the case here.

IMNSHO the only valid annotation for this case is `(in)`.

I have removed (out) annotation from gobject-introspection's gir/gobject-2.0.c and rebuilt goi and now lgi's testsuite pass again as before.

Unfortunately for various reasons (mainly time constraints) I'm not able to pursue this issue with glib/gobject-introspection.  Would you please be able to file bug in gnome bugzilla and possibly push the whole process of fixing glib annotation and importing it into gobject introspection?

However, if gobject-introspection with such incorrect annotation is already out, we should somehow workaround this problem in lgi.  This is not exactly easy, because typical workaround using lgi's poor-man's custom ffi cannot handle array of records, which is needed to handle g_closure_invoke properly and I'd have to come out with some more involved and much uglier hack.

**Comment by psychon** [comment] 2016-05-09 16:37
This issue [reached debain](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823164) and will get lgi [removed from testing in a month](https://udd.debian.org/cgi-bin/autoremovals.cgi).

**Comment by rohieb** [comment] 2016-05-09 22:43
@pavouk, I tried reproducing your "patch" to goi-1.48 (see [Debian bugtracker]()), but it doesn't seem to solve the problem for me.

Also, the commit mentioned by @gregier is part of glib-2.48 according to the Git log, which has already been released (I'm using it on my system). So if that issue is really the one at fault here, it looks like a workaround is needed.

**Comment by gregier** [comment] 2016-05-09 22:48
I agree that obviously (out) is an incorrect annotation for g_closure_invoke(), however looking at the usage I believe the correct annotation is (out caller-allocated) and not (in).

**Comment by rohieb** [comment] 2016-05-09 23:31
Same result with `(out caller-allocated)`.

**Comment by gares** [comment] 2016-05-10 07:44
@psychon, I'm happy to upload to Debian a patched version as soon as I get it!  Thanks for pointing me to this issue ticket.

**Comment by pavouk** [comment] 2016-05-10 07:48
> On 10 May 2016, at 00:43, Roland Hieber <notifications@github.com> wrote:
> 
> @pavouk <https://github.com/pavouk>, I tried reproducing your "patch" to goi-1.48 (see Debian bugtracker <applewebdata://9C041629-098D-4CEF-A4CD-E1D8D6A414FF>), but it doesn't seem to solve the problem for me
> 
> 

Strange.  Just to double check, you applied the ‘patch’ to goi’s glib.c annotations, not glib’s source annotations, right?

> Also, the commit mentioned by @gregier <https://github.com/gregier> is part of glib-2.48 according to the Git log, which has already been released (I'm using it on my system). So if that issue is really the one at fault here, it looks like a workaround is needed.
> 
> 

Bummer.  OK, I’ll have to find time to create another ugly kludge into lgi.  Thanks for the info.

**Comment by pavouk** [comment] 2016-05-10 07:50
> On 10 May 2016, at 00:48, Garrett Regier <notifications@github.com> wrote:
> 
> I agree that obviously (out) is an incorrect annotation for g_closure_invoke(), however looking at the usage I believe the correct annotation is (out caller-allocated) and not (in).
> 
> 

g_closure_invoke specifies that return value must be initialized with expected return type.  This rules out even (out caller-allocated), because that type of annotation does not allow you to pass initialized object.  IMHO the only valid annotation to use here is (in), no matter how strange it looks.

Anyway, given the fact that goi with incorrect annotation is already out in the wild, this point is getting a bit moot.  I’ll have to add workaround into lgi.

**Comment by pavouk** [comment] 2016-05-10 07:56
> On 10 May 2016, at 09:50, Pavel Holejšovský <pavel.holejsovsky@gmail.com> wrote:
> 
> 
>> On 10 May 2016, at 00:48, Garrett Regier <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> I agree that obviously (out) is an incorrect annotation for g_closure_invoke(), however looking at the usage I believe the correct annotation is (out caller-allocated) and not (in).
>> 
>> 
> 
> g_closure_invoke specifies that return value must be initialized with expected return type.  This rules out even (out caller-allocated), because that type of annotation does not allow you to pass initialized object.  IMHO the only valid annotation to use here is (in), no matter how strange it looks.

Err, that’s what I get when I base my opinion on my feelings and real docs.  There is no mention in official docs that g_closure_invoke should have return value type pre-initialized.  So after all, (out caller-allocated) is probably correct annotation.  Sorry for spreading misinformation.

> 
> Anyway, given the fact that goi with incorrect annotation is already out in the wild, this point is getting a bit moot.  I’ll have to add workaround into lgi.

Anyway, this is still valid.

**Comment by rohieb** [comment] 2016-05-12 20:55
On 10.05.2016 09:48, Pavel Holejsovsky wrote:
> Strange. Just to double check, you applied the ‘patch’ to goi’s glib.c
> annotations, not glib’s source annotations, right?

Yes, but to be fair, I have no idea what I'm doing. (I should have said
that up front.)

**Comment by pavouk** [comment] 2016-05-15 18:57
I think I have fixed this issue, at least tests pass and some random lgi samples seem to run fine. Thanks to all for their efforts and reports, and if you try this version, please report back here so that we know whether the issue is really fixed.

**Comment by psychon** [comment] 2016-05-16 00:22
Seems to work here on debian testing (= test suite no longer reports errors, no longer segfaults and it now reports success again).

**Comment by gregier** [comment] 2016-05-16 03:47
Libpeas' Lua plugin loader is working again and all tests pass.

**Comment by psychon** [comment] 2016-05-16 08:38
@pavouk Do you plan on making a new release or should @gares apply these two patches to the debian package? In the end it's his decision what to do in Debian, but a release would also get the fix to other distros.

**Comment by gregier** [comment] 2016-05-16 09:16
Forgot to mention, I'm getting this while building:

```
marshal.c: In function ‘marshal_closure_invoke’:
marshal.c:1842:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (gint i = 0; i < n_params; i++)
   ^
marshal.c:1842:3: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [marshal.o] Error 1
```

**Comment by pavouk** [comment] 2016-05-24 18:48
Pushed simple fix to avoid C99-ism in previous commit, reported by @gregier.
I'm going to make new version in a few days (I have also pushed fix for #133 so I want to be safe if I haven't introduced some fatal flaw there).

**Closed by pavouk** 2016-05-24 18:48 UTC

**Comment by psychon** [comment] 2016-05-25 08:15
Since you are planning a release, let's do some simple tests: I'm on an up-to-date Fedora 23.

With Lua 5.3.2 I get the following warnings from the tests (full output is here: https://gist.github.com/psychon/cd63419b4e1e3770cd5a400fed1fb63b):
```
(process:2824): Lgi-WARNING **: Error raised while calling 'lgi.cbk (number): Regress': attempt to call a number value
(process:2824): Lgi-WARNING **: Error raised while calling 'lgi.cbk (string): Regress': attempt to call a string value
(process:2824): Lgi-WARNING **: Error raised while calling 'lgi.cbk (table: 0x55e2b43d5020): Regress': attempt to call a table value
(process:2824): Lgi-WARNING **: Error raised while calling 'lgi.cbk (table: 0x55e2b42cc3f0): Regress': attempt to call a table value
(lua:2824): GLib-GObject-CRITICAL **: Object class LgiTestFakeMonitor1 doesn't implement property 'network-metered' from interface 'GNetworkMonitor'
```
None of this seems to cause a failure. I don't know if any of this is new, thus I just want to tell you about it.

Next let's try this with LuaJIT. To compile LGI against LuaJIT, I apply https://gist.github.com/psychon/ef05b5ee4085a53e9d27def9b8831203.
"make check" fails:
```
luajit: invalid key to 'next'
stack traceback:
	[C]: at 0x7fd16d851f88
	[C]: in function 'require'
	./lgi/core.lua:14: in main chunk
	[C]: in function 'require'
	./lgi/init.lua:19: in main chunk
	[C]: at 0x5610fb901740
	[C]: in function 'require'
	tests/gireg.lua:11: in main chunk
	[C]: in function 'dofile'
	tests/test.lua:122: in main chunk
	[C]: at 0x5610fb8bd7e0
```
This failure is new and "git bisect" confirms:
```
2a2b60644fed2cc8734ab1bd601f64d8459621c9 is the first bad commit
commit 2a2b60644fed2cc8734ab1bd601f64d8459621c9
Author: Pavel Holejsovsky <pavel.holejsovsky@gmail.com>
Date:   Tue May 24 20:43:54 2016 +0200

    Fix set_resident for Lua 5.3
```
To quote the comment in line 649 of that file:

       /* Note: 'nil' is on the stack from lua_getfield() call above. */

Thus, I suggest the following patch which you can apply with `git am file-containing-the-text`: https://gist.github.com/psychon/cfe6e3280ac6e042536d8a0c13af63e0

Also, unrelated failure that was also present before and likely also in the previous release:
```
cairo   :  4:matrix_init                        FAIL
             tests/cairo.lua:32: got value `6.1232339957368e-17', expected `6.1230317691119e-17'
stack traceback:
	[C]: in function 'error'
	tests/test.lua:88: in function 'fail'
	tests/test.lua:91: in function 'check'
	tests/test.lua:101: in function 'checkv'
	tests/cairo.lua:32: in function 'check_matrix'
	tests/cairo.lua:85: in function <tests/cairo.lua:70>
	[C]: in function 'xpcall'
	tests/test.lua:50: in function 'runfunc'
	tests/test.lua:73: in function 'run'
	tests/test.lua:141: in main chunk
	[C]: at 0x564d1e3bd7e0
```
(Should the test do an inexact comparison? The values are quite close to each other.)

Besides this, the results are the same as with Lua 5.3.

**Comment by pavouk** [comment] 2016-05-25 19:26
@psychon  Thanks a lot!  I applied your patch for my .. erm.. brainfart. Also fixed matrix testcase running with luajit and fixed yet another breakage uncovered in gdk-demo.  I plan to release lgi 0.10.0 probably on friday, if no new showstopper appears.

The rest of testsuite 'failure messages' you mentioned are expected.At least for inheritance test complaining about unimplemented interface property, the test could be improved to avoid this warning, but nothing breaks (at least yet) with current state of affairs.

**Comment by psychon** [comment] 2016-05-26 07:20
"make check" is now happy both with Lua 5.3.2 and with LuaJIT 2.0.4. Thanks! I didn't try any of the demos, tell me if I should.
