### ISSUE TITLE
Can't connect to http://addons.supertuxkart.net/api/v2/server/get-all

### ISSUE THREAD

**Issue by v1993** [pavouk/lgi#205] opened 2018-09-24 04:00 UTC
I try to connect to STK API endpoint using Gio:

	local file = Gio.File.new_for_uri(uri)
	local info = file:async_query_info('standard::size', 'NONE')
	local stream = file:async_read()
	if stream then
		local bytes = stream:async_read_bytes(info:get_size())
		stream:async_close()
		…
	end
It works just fine for my static example on http://stktest.vallua.ru/api/v2/server/get-all or local file (file:///), but fails on real one http://addons.supertuxkart.net/api/v2/server/get-all.

Error is thrown by `stream:async_read_bytes(info:get_size())` (same thing for sync version and other read function).

    (lua:17037): GLib-GIO-CRITICAL **: 06:42:10.475: g_input_stream_read_async: assertion 'buffer != NULL' failed

**Comment by v1993** [comment] 2018-09-24 12:00
Ok, source of problem is zero `info:get_size()`. I'll google on it…

**Comment by psychon** [comment] 2018-09-24 15:11
First: I would doubt that is due to lgi and not Gio.

Second: Since you already have this, can you provide some (small-ish) self-contained, runnable example that reproduces your problem? That would likely be faster for you than if I try to come up with something like that on my own.

**Comment by v1993** [comment] 2018-09-24 15:17
local lgi = require 'lgi'
	local Gio = lgi.Gio
	local file = Gio.File.new_for_uri('http://addons.supertuxkart.net/api/v2/server/get-all')
	local info = file:query_info('standard::size', 'NONE')
	local stream = file:read()
	if stream then
		local bytes = stream:read_bytes(info:get_size())
		stream:async_close()
		print(bytes.data)
	end
My solution is to run read loop and download 2KB blocks until length is zero.

**Comment by psychon** [comment] 2018-09-24 15:29
Small change to your example:
```diff
--- t.lua.orig	2018-09-24 17:25:03.708281089 +0200
+++ t.lua	2018-09-24 17:25:05.056258697 +0200
@@ -1,7 +1,8 @@
 local lgi = require 'lgi'
 local Gio = lgi.Gio
 local file = Gio.File.new_for_uri('http://addons.supertuxkart.net/api/v2/server/get-all')
-local info = file:query_info('standard::size', 'NONE')
+local info, err = file:query_info('standard::size', 'NONE')
+print(info, err)
 local stream = file:read()
 if stream then
 	local bytes = stream:read_bytes(info:get_size())
```
Result (for me):
```
nil	Operation not supported
```
So, this seems to be a combination of missing error checking on your end (and I do not see any HTTP requests in `strace`, so perhaps Gio does not even support querying the size of HTTP resources).

Do you get the same result?

Also, note that you seem to be mis-using `async_*`, but if you actually hit this code, the error message will tell you. These function can only be used from a specially prepared coroutine, see LGI's Gio docs (search for `Gio.start` and `Gio.call`). This special support allows to turn callback-based spaghetti code into nice looking, linear code. To the coroutine, the call will still appear to block, but other coroutines can run in this time.

**Comment by v1993** [comment] 2018-09-24 15:49
I know about async, thanks. Try this code with http://stktest.vallua.ru/api/v2/server/get-all, and it will work.

**Comment by psychon** [comment] 2018-09-24 16:43
Same error for me and still no network activity visible in `strace`.
If I `print(file)`, It says this is an object of type `GDummyFile`. This does not sound to me like it could possibly work. Perhaps some extra package is needed for network support in Gio...? Dunno.

**Comment by v1993** [comment] 2018-09-24 17:11
It actually works for me. Try passing non-zero value to `stream:read_bytes`, like 2048.

**Comment by psychon** [comment] 2018-09-24 18:02
```lua
local lgi = require 'lgi'
local Gio = lgi.Gio
local file, err = Gio.File.new_for_uri('http://stktest.vallua.ru/api/v2/server/get-all')
print(file, err)
local info, err = file:query_info('standard::size', 'NONE')
print(info, err)
local stream, err = file:read()
print(stream, err)
if stream then
	local bytes = stream:read_bytes(2048)
	stream:async_close()
	print(bytes.data)
else
	print("else")
end
```
```
lgi.obj 0x55e883609530:GObject.Object(GDummyFile)	nil
nil	Operation not supported
nil	Operation not supported
else
```

**Comment by Elv13** [comment] 2018-09-24 19:35
Note that when using some of these classes, the result will vary depending if the gvfs daemon is running or not. This may explain why you can't reproduce each other results.

**Comment by psychon** [comment] 2018-09-25 05:00
I tried installing gvfs yesterday. That did not make a difference. However, I did not install `gvfs-backends` and according to the package description, this package contains the HTTP backend.

Anyway, I now tried on another computer and here both URLs just work, but the "non-working" one returns `0` for the file size. I `strace`'d the `gvfsd-http` process. Here is the HTTP request it sends:
```
sendto(8, "HEAD /api/v2/server/get-all HTTP/1.1\r\nHost: addons.supertuxkart.net\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: gvfs/1.36.2\r\nAccept-Language: de-de, de;q=0.9\r\nConnection: Keep-Alive\r\n\r\n", 186, MSG_NOSIGNAL, NULL, 0)
```
and this is the answer:
```
recvfrom(8, "HTTP/1.1 200 OK\r\nDate: Tue, 25 Sep 2018 04:56:26 GMT\r\nServer: Apache\r\nKeep-Alive: timeout=5, max=100\r\nConnection: Keep-Alive\r\nContent-Type: text/xml;charset=UTF-8\r\n\r\n", 8192, 0, NULL, NULL)
```
So... this seems to be the HTTP server just not providing a file length in response to `HEAD` requests (whoops, I previously tried HEADER). Thus, gvfs cannot provide a file length without downloading the response.

I'd say that the "fix" here is to read from the stream that you can open until EOF is reached, but, if I understood you correctly, you already came to the same conclusion.

Was everything now debugged or is there still something missing?

**Comment by v1993** [comment] 2018-09-25 11:49
Yes, thank you.

> but the "non-working" one returns 0 for the file size

I've said this before:

> Ok, source of problem is zero `info:get_size()`.

BTW, can you look at https://github.com/pavouk/lgi/pull/161, please?

**Comment by psychon** [comment] 2018-09-25 13:39
Ah, okay. So since there is nothing left here, I'll close this.

> BTW, can you look at #161, please?

I still got an unread notification for that one with GitHub. Will take a look once I have some time (looking at all the other issues seemed like it would require less time than looking at a pull request).

**Closed by psychon** 2018-09-25 13:39 UTC
