### ISSUE TITLE
Segfault with ffi.load('gettextlib').

### ISSUE THREAD

**Issue by v1993** [pavouk/lgi#145] opened 2016-10-29 13:22 UTC
This code throws segfalt:

```
local ffi = require 'ffi'
gettext = ffi.load('gettextlib')
local lgi = require 'lgi'
```

I'm using linux mint 18, gettext 0.19.7, lua 5.2 with ffib from https://github.com/facebook/luaffifb, lgi from luarocks. What's wrong? If I will load gettext after lgi, all is ok.

**Comment by psychon** [comment] 2016-10-29 13:40
Which gettext library are you loading there? It seems to be part of the problem.
The following works fine here: `lua5.1 -e 'gettext = require("ffi").load("xcb") require("lgi") print("done")`

**Comment by v1993** [comment] 2016-10-29 13:43
I've got this problem only with gettext.
    ls -l /usr/lib/x86_64-linux-gnu/libgettextlib.so
    lrwxrwxrwx 1 root root 23 Jul  1 13:45 /usr/lib/x86_64-linux-gnu/libgettextlib.so -> libgettextlib-0.19.7.so

**Comment by psychon** [comment] 2016-10-29 13:46
In that case you must be on some Ubuntu version that I don't have access to. There is no such file in any Debian package (and the path suggests that you are using Debian or some Debian derivative).
http://packages.ubuntu.com/search?suite=xenial&arch=amd64&mode=exactfilename&searchon=contents&keywords=libgettextlib.so

**Comment by v1993** [comment] 2016-10-29 13:54
I'm sorry for wrong library name in `ffi.load`, it's really `gettextlib`.

**Comment by v1993** [comment] 2016-10-29 13:56
I found it: http://packages.ubuntu.com/search?mode=exactfilename&suite=xenial&section=all&arch=amd64&keywords=libgettextlib.so&searchon=contents.

**Comment by psychon** [comment] 2016-10-29 14:28
Ok, I can reproduce with `lua5.1 -e 'gettext = require("ffi").load("gettextlib-0.19.8.1") require("lgi")'`. However, no idea why this crashes. It crashes [here](https://github.com/pavouk/lgi/blob/1024e5200a515614d3d321991934b685d2b44cd7/lgi/ffi.lua#L24) which seems to just be the first call to `gi.require`. The crash is inside of `g_irepository_require` which calls some function which calls some function which causes `g_hash_table_destroy` to dereference a NULL pointer.

Dunno, sorry.

**Comment by psychon** [comment] 2016-10-29 14:50
Seems to be a problem with `libgettextlib`. It exports its own version of glib symbols, for example:
```
$ nm --dynamic /usr/lib/libgettextlib-0.19.8.1.so | grep g_hash_table_new
000000000002be50 T g_hash_table_new
000000000002bde0 T g_hash_table_new_full
```
That does not seem correct.

**Comment by psychon** [comment] 2016-10-29 15:18
Why are you loading `libgettextlib` at all? What are you doing with it? It seems to be more or less an implementation detail of gettext that should not be used on its own.

Anyway, this library exports `g_hash_table_new`, but does not export `g_hash_table_destroy`, so the version of libgettextlib is used to create the hash table, but the "real" function is used to destroy it again. Looking at the source code, the ABI here is different. libgettextlib uses
```c
typedef struct hash_table
{
  unsigned long int size;   /* Number of allocated entries.  */                                                           
  unsigned long int filled; /* Number of used entries.  */
  struct hash_entry *first; /* Pointer to head of list of entries.  */
  struct hash_entry *table; /* Pointer to array of entries.  */
  struct obstack mem_pool;  /* Memory pool holding the keys.  */
}
```
Current glib uses
```c
struct _GHashTable
{
  gint             size;
  gint             mod;
  guint            mask;
  gint             nnodes;
  gint             noccupied;  /* nnodes + tombstones */

  gpointer        *keys;
  guint           *hashes;
  gpointer        *values;

  GHashFunc        hash_func;
  GEqualFunc       key_equal_func;
  gint             ref_count;
#ifndef G_DISABLE_ASSERT
  /*
   * Tracks the structure of the hash table, not its contents: is only
   * incremented when a node is added or removed (is not incremented
   * when the key or data of a node is modified).
   */
  int              version;
#endif
  GDestroyNotify   key_destroy_func;
  GDestroyNotify   value_destroy_func;
};
```
I reported https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842478 and propose that this bug report against lgi is closed.

**Comment by v1993** [comment] 2016-10-29 15:53
I'm using gettext below, but this code just crashes.

**Comment by psychon** [comment] 2016-10-29 16:06
Then you are loading the wrong library. `gettextlib` is not meant to be used by anything except for gettext's own tools. Are you perhaps looking for libintl (`load("intl")`) or libc? Do you have some more lines of code to look at?

**Comment by psychon** [comment] 2016-10-29 16:15
Does perhaps the following help you?
```Lua
ffi = require("ffi")
ffi.cdef("const char* gettext(const char* text);")
print(ffi.string(ffi.C.gettext("foo")))'
```

**Comment by v1993** [comment] 2016-10-29 17:02
In fact, I'm using library from https://raw.githubusercontent.com/bungle/lua-resty-gettext/master/lib/resty/gettext.lua. I found this code:
    local ok, lib = pcall(ffi_load, "intl")
    if not ok then
        ok, lib = pcall(ffi_load, "gettextlib")
        if not ok then
            lib = C
        end
    end
Before, `ffi_load = ffi.load`

**Comment by pavouk** [comment] 2016-11-17 10:18
It seems to me that the issue is quite clear, loading gettextlib into global process namespace causes issues because of symbols coming from gettextlib clash with proper ones from glib.  This has nothing to do with lgi and IMO it is clear cockpit error.  I'll close this issue soon unless someone will raise objections with new facts. :-)

**Closed** 2017-03-14 15:35 UTC
