### ISSUE TITLE
Bad argument #1 to 'registerlock' (userdata expected, got nil)

### ISSUE THREAD

**Issue by MattiaSilvestri** [pavouk/lgi#269] opened 2021-07-24 21:15 UTC
I use Manjaro with awesome-git as window manager (v4.3-1066-g832483dd6) and until now it always worked fine. However, I recently ran an update and now I'm not able to access awesome anymore because I get this error message at login: `/usr/share/lua/5.3/lgi/override/Gdk.lua:23: bad argument #1 to 'registerlock' (userdata expected, got nil)` 
I opened an [issue](https://github.com/awesomeWM/awesome/issues/3394#event-5041820288) on the awesome github page and, since apparently it already happened to another Manjaro user in the past, they say the problem it's not related to the WM but to either Manjaro or LGI itself. I still didn't get much help from the Manjaro community and now I'm quite desperate because it's more than a week that I cannot access my WM (using Gnome in the meanwhile). I'm not a tech expert and I don't even know what LGI does for awesome, but my understanding is that the problem seems to be related to this package. Any insight is really appreciated! And please tell me if you think this issue is not strictly related to LGI and therefore should not be solved here.

**Comment by psychon** [comment] 2021-07-25 05:08
As already written in https://github.com/awesomeWM/awesome/issues/3394#issuecomment-882297613: LGI does not work with Gtk 4 and this is a duplicate of #226. Sorry.

**Closed by psychon** 2021-07-25 05:08 UTC

**Comment by swiftgeek** [comment] 2021-08-07 16:29
This case might be a bit different, GTK4 (4.2.1 in my example) installed alongside GTK3 (3.24.30)
