### ISSUE TITLE
Not GCing DBusProxies

### ISSUE THREAD

**Issue by otommod** [pavouk/lgi#189] opened 2018-01-25 13:47 UTC
So, I don't know if this is a bug in lgi, if it's specific to `DBusProxy` or if I'm just stupid, but I have this code to make proxies of MPRIS players.
```lua
local players = {}

local bus = gio.bus_get_sync(gio.BusType.SESSION)

local function add_player(name)
    local proxy, err = gio.DBusProxy.new_sync(
        bus,
        gio.DBusProxyFlags.NONE,
        nil,
        name,
        "/org/mpris/MediaPlayer2",
        "org.mpris.MediaPlayer2.Player")
    -- if err then error(err) end

    proxy.on_notify["g-name-owner"] = function()
        if not proxy.g_name_owner then
            print("on_notify: dead: " .. tostring(proxy.g_name))
            players[name] = nil
        end
    end

    players[name] = proxy
    return proxy
end

bus:signal_subscribe(
    "org.freedesktop.DBus",   -- name
    "org.freedesktop.DBus",   -- interface
    "NameOwnerChanged",       -- signal
    "/org/freedesktop/DBus",  -- path
    "org.mpris.MediaPlayer2", -- namespace of names we'le listening to
    gio.DBusSignalFlags.MATCH_ARG0_NAMESPACE,
    function(conn, sender, path, iface, signal, args)
        local name, prev_owner, owner = unpack(args)
        local player_name = name:sub(1 + #"org.mpris.MediaPlayer2.")
        if prev_owner == "" then
            -- name acquired
            add_player(name)
        elseif owner == "" then
            -- name lost
        else
            -- someone took over the name
        end
    end)
```

The problem is that, even after `players[name] = nil`, when there shouldn't be any references left, it still "sticks around".  So when a player with the same name shows up again and then dies, I now get two `print()`.  And then 3 the third time it dies and so on.

Oh and if I try to manually unref I get a crash.  I'm running all this in awesome without debug symbols unfortunately so the trace doesn't make too much sense...

**Comment by psychon** [comment] 2018-01-25 14:08
> The problem is that, even after players[name] = nil, when there shouldn't be any references left, it still "sticks around". 

What happens if you add a `collectgarbage("collect")`? The garbage collector works lazily. It doesn't immediately free everything that becomes unreachable (that would be too slow).

Also, if a single `collectgarbage("collect")` doesn't work, how about five in a row?

And no, please do not do the above at the same position where you do `players[name] = nil`. At that point the stack will keep things alive. If you are still doing this in awesome:
```lua
gears.timer.start_new(0, function()
    for i=1, 10 do collectgarbage("collect") end
end))
```

I can't easily debug this since I do not use MPRIS, but perhaps the above already explains this?

**Comment by otommod** [comment] 2018-01-25 14:24
That doesn't work either.

**Comment by psychon** [comment] 2018-01-25 15:07
Okay, I took a closer look. The reference loop is between the proxy and the signal connection. Apparently this is done in a way that the GC does not see that the function is only kept alive by the proxy. Thus, both are kept alive.

A work around seems to be using a weak table:
```lua
    local weak = setmetatable({}, { __mode = "v" })
    weak.proxy = proxy
    proxy.on_notify["g-name-owner"] = function()
        local proxy = weak.proxy
        if proxy and not proxy.g_name_owner then
            print("on_notify: dead: " .. tostring(proxy.g_name))
            players[name] = nil
        end
    end
```

**Comment by otommod** [comment] 2018-01-25 16:08
That works indeed, but I just ended up disconnecting the signals by hand.

I thought that cycles wouldn't be a problem, since Lua uses a GC but forgot GLib uses reference counting, could that be it?  It's weird though, if I made the signal handlers use `self` instead of referencing `proxy` I they would still "linger", so why does a weak table work?

**Comment by psychon** [comment] 2018-01-26 07:11
I haven't digged too deep into LGI's code, but the callback function is kept alive by the registry. So I guess that LGI does a `luaL_ref` on the callback function and saves the result (a number, let's say 42) somewhere in the proxy object. Now, the proxy object only has a reference to "42" while the callback function is kept alive by the registry and in turn keeps the proxy object alive.

Since the GC cannot know that collecting the proxy object makes it `luaL_unref` the callback function, nothing can be collected.

(The above is a simplification of the situation. I quickly stopped digging deeper, but the function is kept alive through 'lgi.override.GObject-Closure`, the function returned by `:get_closure_marshaller(target)`. It is actually this function which can be somehow reached through the registry.)

Oh and: I'll close this as a duplicate of https://github.com/pavouk/lgi/issues/55#issuecomment-20140352

**Closed by psychon** 2018-01-26 07:11 UTC
