### ISSUE TITLE
Segmentation fault in Gio.File.copy_async

### ISSUE THREAD

**Issue by sclu1034** [pavouk/lgi#285] opened 2022-03-16 13:41 UTC
The following snippet will always fail with a `segmentation fault` or `illegal hardware instruction`:

```lua
local lgi = require("lgi")
local Gio = lgi.Gio

local src = Gio.File.new_for_path("/tmp/foo")
local dest = Gio.File.new_for_path("/tmp/bar")

local loop = lgi.GLib.MainLoop.new()

src:copy_async(dest, Gio.FileCopyFlags.NONE, 0, nil, nil, function(_, token)
    local ok, err = src:copy_finish(token)
    print(ok, err)
    loop:quit()
end)

loop:run()
```

The sync version `Gio.File.copy` works fine, as does the C equivalent to above:

```c
#include <glib-2.0/glib.h>
#include <glib-2.0/gio/gio.h>
#include <stdio.h>

typedef struct
{
  GError *error;
  gboolean done;
  gboolean res;
} Data;


static void
cb (GObject      *object,
    GAsyncResult *result,
    gpointer      user_data)
{
  GFile *file = G_FILE (object);
  Data *data = user_data;
  GError *error = NULL;

  data->res = g_file_copy_finish(file, result, &error);
  data->error = error;
  data->done = TRUE;
}


int main() {
    GFile* src = g_file_new_for_path("/tmp/foo");
    GFile* dest = g_file_new_for_path("/tmp/bar");
    Data data = { 0 };

    g_file_copy_async(src, dest, G_FILE_COPY_NONE, 0, NULL, NULL, NULL, cb, &data);

    while (!data.done)
        g_main_context_iteration (NULL, TRUE);

    if (!data.res)
        printf("%s\n", data.error->message);
}
```

**Versions:**
```shell
$ lua -v
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio

$ luarocks list lgi
Rocks installed for Lua 5.3
---------------------------

lgi
   0.9.2-1 (installed) - $HOME/.luarocks/lib/luarocks/rocks-5.3

$ uname -a
Linux *** 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by psychon** [comment] 2022-03-16 15:53
```
Breakpoint 3, g_file_copy_async (source=0x555555655ea0, destination=0x555555655ec0, flags=G_FILE_COPY_NONE, io_priority=0, cancellable=0x0, progress_callback=0x7ffff7fbc100, 
    progress_callback_data=0x7ffff7fbc178, callback=0x7ffff7fbc1f0, user_data=0x7ffff7fbc268) at ../../../gio/gfile.c:3591
```
Uhm, what? Why does this set both callbacks?

So, which callback crashes...?
```
Breakpoint 3, g_file_copy_async (source=0x5555556562a0, destination=0x5555556562c0, flags=G_FILE_COPY_NONE, io_priority=0, cancellable=0x0, progress_callback=0x7ffff7fbc100, 
    progress_callback_data=0x7ffff7fbc178, callback=0x7ffff7fbc1f0, user_data=0x7ffff7fbc268) at ../../../gio/gfile.c:3591
3591	../../../gio/gfile.c: Datei oder Verzeichnis nicht gefunden.
(gdb) break *0x7ffff7fbc100
Breakpoint 4 at 0x7ffff7fbc100
(gdb) break *0x7ffff7fbc1f0
Breakpoint 5 at 0x7ffff7fbc1f0
(gdb) c
Continuing.
[New LWP 33218]
[New LWP 33219]

Thread 1 "lua5.3" hit Breakpoint 5, 0x00007ffff7fbc1f0 in ?? ()
```
That's `callback`, not `progress_callback`. Okay..

The code at that address doesn't look good:
```
(gdb) disassemble 0x00007ffff7fbc1f0, 0x00007ffff7fbc2f0
Dump of assembler code from 0x7ffff7fbc1f0 to 0x7ffff7fbc2f0:
=> 0x00007ffff7fbc1f0:	add    %al,(%rax)
   0x00007ffff7fbc1f2:	add    %al,(%rax)
   0x00007ffff7fbc1f4:	add    %al,(%rax)
   0x00007ffff7fbc1f6:	add    %al,(%rax)
   0x00007ffff7fbc1f8:	add    %al,(%rax)
   0x00007ffff7fbc1fa:	add    %al,(%rax)
   0x00007ffff7fbc1fc:	add    %al,(%rax)
   0x00007ffff7fbc1fe:	add    %al,(%rax)
   0x00007ffff7fbc200:	add    %al,(%rax)
   0x00007ffff7fbc202:	add    %al,(%rax)
   0x00007ffff7fbc204:	add    %al,(%rax)
   0x00007ffff7fbc206:	add    %al,(%rax)
   0x00007ffff7fbc208:	add    %al,(%rax)
   0x00007ffff7fbc20a:	add    %al,(%rax)
   0x00007ffff7fbc20c:	add    %al,(%rax)
   0x00007ffff7fbc20e:	add    %al,(%rax)
   0x00007ffff7fbc210:	add    %al,(%rax)
   0x00007ffff7fbc212:	add    %al,(%rax)
   0x00007ffff7fbc214:	add    %al,(%rax)
   0x00007ffff7fbc216:	add    %al,(%rax)
   0x00007ffff7fbc218:	add    %al,(%rax)
   0x00007ffff7fbc21a:	add    %al,(%rax)
   0x00007ffff7fbc21c:	add    %al,(%rax)
   0x00007ffff7fbc21e:	add    %al,(%rax)
   0x00007ffff7fbc220:	add    %al,(%rax)
   0x00007ffff7fbc222:	add    %al,(%rax)
   0x00007ffff7fbc224:	add    %al,(%rax)
   0x00007ffff7fbc226:	add    %al,(%rax)
   0x00007ffff7fbc228:	lock sar $0xf7,%ebx
   0x00007ffff7fbc22c:	(bad)  
   0x00007ffff7fbc22d:	jg     0x7ffff7fbc22f
[...]
(gdb) x /100bx 0x00007ffff7fbc1f0
0x7ffff7fbc1f0:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x7ffff7fbc1f8:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x7ffff7fbc200:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x7ffff7fbc208:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x7ffff7fbc210:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x7ffff7fbc218:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x7ffff7fbc220:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x7ffff7fbc228:	0xf0	0xc1	0xfb	0xf7	0xff	0x7f	0x00	0x00
0x7ffff7fbc230:	0xf0	0xc1	0xfb	0xf7	0xff	0x7f	0x00	0x00
0x7ffff7fbc238:	0x00	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x7ffff7fbc240:	0xa8	0x22	0x59	0x55	0x55	0x55	0x00	0x00
0x7ffff7fbc248:	0x0b	0x00	0x00	0x00	0x00	0x00	0x00	0x00
0x7ffff7fbc250:	0x88	0xe1	0x5a	0x55
```
Yeah... dunno...

**Comment by psychon** [comment] 2022-03-16 16:36
I am confused. As in "how does this ever work?!?"-confused.

This code here:

https://github.com/lgi-devs/lgi/blob/9eaad42eec50baa3e24f3420c35107d6d295577e/lgi/callable.c#L872-L879

Allocates a closure for each of `progress_callback`, `progress_callback`data`, `callback` and `user_data`. And for none of them does this make any sense. The closure is some struct and not executable code. Something still has to call `lgi_closure_create` and the return value of that function is the function pointer to use.

I *guess* that this call should happen somewhere in the following loop (at least I could see how one could end up with a call to `lgi_closure_create` through the marshalling code), but since all arguments were marked as `internal`, nothing happens there.

How is this supposed to work?!

**Comment by psychon** [comment] 2022-03-16 16:43
That "mark as internal" happens here:
https://github.com/lgi-devs/lgi/blob/9eaad42eec50baa3e24f3420c35107d6d295577e/lgi/callable.c#L391-L402

According to the comment next to this (and also according to https://gnome.pages.gitlab.gnome.org/gobject-introspection/girepository/gi-GIArgInfo.html#g-arg-info-get-closure), given a function pointer argument, this should figure out the index of the argument with the `user_data` for this callback. However, in this case the function points to the user data (as expected), and the user data points back at the function. This later thing is why things go downhill...

**Comment by ntd** [comment] 2022-04-11 09:09
This is likely a duplicate of #241 (and #262). With the current code, I think any API with a progress callback (and not explicitely overriden by LGI) will trigger a crash, even if you do not set that callback.

There is a [known upstream issue](https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/25) that prevents proper handling of progress callbacks and it is by no means specific to Lua (see e.g. [this Python issue](https://gitlab.gnome.org/GNOME/pygobject/-/issues/382)).

**Closed as completed** 2022-05-25 15:49 UTC
